version: "3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/go/src/app
    environment:
      MYSQL_USER: "webuser"
      MYSQL_PASSWORD: "webpass"
      MYSQL_HOST: "db"
      MYSQL_DATABASE: "go_mysql8_development"
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - go_mysql_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: "webuser"
      MYSQL_PASSWORD: "webpass"
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: "go_mysql8_development"
volumes:
  go_mysql_data:
